services:
  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    ports:
      - "5672:5672"   # Porta RabbitMQ
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
  postgresql:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 5432:5432
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: valkey/valkey:8.1.0-alpine
    ports:
      - 6379:6379
